const exclude = [
  "American Robin",
  "Mourning Dove",
  "Northern Cardinal",
  "Blue Jay",
  "Red-winged Blackbird",
  "European Starling",
  "American Goldfinch",
  "House Sparrow",
  "Canada Goose",
  "Common Grackle",
  "Downy Woodpecker",
  "Northern Flicker",
  "Dark-eyed Junco",
  "House Finch",
  "Mallard",
  "White-breasted Nuthatch",
  "Red-tailed Hawk",
  "Black-capped Chickadee",
  "Red-bellied Woodpecker",
  "Killdeer",
  "Eurasian Collared-Dove",
  "Barn Swallow",
  "American Crow",
  "Western Meadowlark",
  "Brown-headed Cowbird",
  "House Wren",
  "Turkey Vulture",
  "Eastern Kingbird",
  "Great Blue Heron",
  "Baltimore Oriole",
  "Song Sparrow",
  "Chipping Sparrow",
  "Blue-winged Teal",
  "Yellow Warbler",
  "Gray Catbird",
  "Ring-billed Gull",
  "Red-headed Woodpecker",
  "Brown Thrasher",
  "Bald Eagle",
  "Northern Shoveler",
  "Rock Pigeon",
  "Common Yellowthroat",
  "Dickcissel",
  "American Coot",
  "American Tree Sparrow",
  "Ring-necked Pheasant",
  "Wood Duck",
  "Eastern Bluebird",
  "American Kestrel",
  "Hairy Woodpecker",
  "Warbling Vireo",
  "Orchard Oriole",
  "Wild Turkey",
  "Belted Kingfisher",
  "Cedar Waxwing",
  "Double-crested Cormorant",
  "Western Kingbird",
  "Gadwall",
  "Harris's Sparrow",
  "Yellow-rumped Warbler",
  "Tree Swallow",
  "Green-winged Teal",
  "Cliff Swallow",
  "Pied-billed Grebe",
  "Horned Lark",
  "Chimney Swift",
  "Field Sparrow",
  "Lark Sparrow",
  "Lesser Scaup",
  "Eastern Meadowlark",
  "Snow Goose",
  "Red-eyed Vireo",
  "Eastern Phoebe",
  "Ring-necked Duck",
  "American White Pelican",
  "American Wigeon",
  "Red-breasted Nuthatch",
  "Northern Rough-winged Swallow",
  "White-throated Sparrow",
  "Rose-breasted Grosbeak",
  "Northern Bobwhite",
  "Bufflehead",
  "Great Crested Flycatcher",
  "Redhead",
  "Ruddy Duck",
  "Spotted Towhee",
  "Northern Harrier",
  "White-crowned Sparrow",
  "Indigo Bunting",
  "Franklin's Gull",
  "Northern Pintail",
  "Lincoln's Sparrow",
  "Eastern Wood-Pewee",
  "Spotted Sandpiper",
  "Grasshopper Sparrow",
  "Common Goldeneye",
  "Cooper's Hawk",
  "Orange-crowned Warbler",
  "Pine Siskin",
  "Cackling Goose",
  "Carolina Wren",
  "Lesser Yellowlegs",
  "Sandhill Crane",
  "Common Merganser",
  "Yellow-headed Blackbird",
  "Eastern Towhee",
  "American Redstart",
  "Swainson's Thrush",
  "Bell's Vireo",
  "Greater Yellowlegs",
  "Purple Martin",
  "Least Flycatcher",
  "Clay-colored Sparrow",
  "Common Nighthawk",
  "Ruby-throated Hummingbird",
  "Ruby-crowned Kinglet",
  "Great Horned Owl",
  "Blue Grosbeak",
  "Tufted Titmouse",
  "Hooded Merganser",
  "Greater White-fronted Goose",
  "Canvasback",
  "Least Sandpiper",
  "Wilson's Phalarope",
  "Upland Sandpiper",
  "Savannah Sparrow",
  "Blue-gray Gnatcatcher",
  "Baird's Sandpiper",
  "Pectoral Sandpiper",
  "Bank Swallow",
  "Swainson's Hawk",
  "American Herring Gull",
  "Vesper Sparrow",
  "Great-tailed Grackle",
  "Nashville Warbler",
  "Black Tern",
  "Wilson's Snipe",
  "Osprey",
  "Barred Owl",
  "Semipalmated Sandpiper",
  "Brown Creeper",
  "Tennessee Warbler",
  "Marsh Wren",
  "American Avocet",
  "Western Grebe",
  "Sharp-shinned Hawk",
  "Forster's Tern",
  "Green Heron",
  "Great Egret",
  "Eared Grebe",
  "Yellow-throated Vireo",
  "Solitary Sandpiper",
  "Long-billed Dowitcher",
  "Swamp Sparrow",
  "Wilson's Warbler",
  "Wood Thrush",
  "Fox Sparrow",
  "White-faced Ibis",
  "Willow Flycatcher",
  "Ross's Goose",
  "Black-and-white Warbler",
  "Yellow-breasted Chat",
  "Western Wood-Pewee",
  "Lark Bunting",
  "Red Crossbill",
  "Loggerhead Shrike",
  "Stilt Sandpiper",
  "Red-breasted Merganser",
  "Semipalmated Plover",
  "Willet",
  "White-rumped Sandpiper",
  "Horned Grebe",
  "Summer Tanager",
  "Northern Shrike",
  "Common Loon",
  "Blue-headed Vireo",
  "Hudsonian Godwit",
];

export default exclude;
